const categoryNames = [
  'Approval',
  'AddLiquidity',
  'RemoveLiquidity',
  'Stake',
  'UnStake',
  'Deposit',
  'Withdraw',
  'Borrow',
  'Repay',
  'Lend',
  'Collect',
  'Liquidate',
  'Liquidated',
  'Purchase',
  'Sell',
  'Swap',
  'Transfer/Send',
  'Bid',
  'Mint',
  'Burn',
  'Claim',
  'Bridge',
  'UnBridge',
  'Wrap',
  'UnWrap',
  'NULL (Contracts Not Worth Tracking)',
];
const categoryNotes = [
  'Has to happen before another contract can act on the token',
  'Line 5 is the most complex case, the tokens are actually hard coded that it takes, Line 11 is a more straightforward case of addliquidity)',
  '',
  'Would likely happen AFTER an approval to the same address',
  '',
  'Tricky, this can also trigger a "claim" so a scenario of the stacking classifications.',
  '',
  '',
  '',
  'this is going to look very similar to staking how do we tell the diff?',
  '',
  '',
  '',
  '',
  '',
  '',
  'Between this and Stake - the action is sending to another wallet address not a contract address ',
  '',
  'The token being sent in the Transfer event will be address(0) the same address that is minting',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
];

module.exports = {
  categoryNames,
  categoryNotes,
};
